---
title: "Datan rukkailua 2"
output:
  pdf_document: default
  html_document: default
---
```{r}
library(rgl)
library(ca)
library(haven)
library(dplyr)
library(knitr)
library(tidyverse)
library(lubridate)
library(rmarkdown)
library(ggplot2)
library(furniture)
library(likert)
library(scales) # G_1_2 - kuva
library(reshape2)  # G_1_2 - kuva
library(printr) #19.5.18 taulukoiden ja matriisien tulostukseen
library(stargazer) # 28.5.2018 taulukoiden yms. tulostietojen siistiin tulostukseen
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = FALSE, include = FALSE)
```

R-skriptist채 Markdowniin, tulostusoptioiden testailua

# 5. Siistit taulukot ja tulosteet
```{r}
star2 <- summary(simpleCA1)
str(star2)
```


Stargazer-paketilla CA-tuloksia, mutta eiv채t kulje html-tiedostoon asti.Ei toimi oikein mitenk채채n (2.7.2018)?

```{r tahti1, results = "asis"}
#star1 <- print(simpleCA1)
#str(star1)


#stargazer(star2$scree, type="text")
#stargazer(star2$rows, type="html")
stargazer(star2$columns, header=FALSE, type='latex')
```

