---
title: "Käsitteet"
output:
  pdf_document: default
  html_document:
    df_print: paged
lang: fi
---

```{r}
library(tidyverse)
library(knitr)
```

# Käsitteet

1.8.2018

Kerätään käsitteet yhteen dataframeen, taulukon tai taulkoiden luontia varten.

```{r kasitteet1Tau1, fig.cap="Korrespondenssianalyysin käsitteet"}
consepts_fi <- c("massa", "profiili", "kontrasti", "modaliteetit", "attraktio",
               "repulsio", "barysentrinen", "ekvivalenssi jakauman suhteen",
               "pääkoordinaatit", "standardikoordinaatit", "inertia")
consepts_en <- c("mass", "profile","contrast","modalities","attraction",
                 "repulsion","barycentric", "distributional equivalence",
                 "principal coordinates", "stardard coordinates", "inertia"
                 )

consepts_meaning <- c("massa, havaintojen lukumäärä", "profiili,jotain", "ääripäät",
                      "luokittelumuuttujan arvo tai arvot", "vetovoima", "työntövoima", 
                      "painotettu keskiarvo","jakauman ekvivalenssi on tärkein periaate",
                      "skaalaus a", "skaalaus b", "hajonnan tunnusluku")
#consepts_remark <- c("absoluuttinen tai suhteellinen", "rivin/sarakkeen havaintojen suhteellinen     #jakauma","ääripäät","luokittelumuuttujan arvo tai arvot", "vetovoima", "työntövoima", 
#                      "painotettu keskiarvo","jakauman ekvivalenssi on tärkein periaate",
#                      "skaalaus a", "skaalaus b", "hajonnan tunnusluku")
## Ei hyvä idea, taulukosta tulee liian leveä. Selitykset tekstiin, ei taulukkoon ängettyinä

# luodaan df concepts1
consepts1.df <- data_frame(consepts_fi,consepts_en,consepts_meaning)
cols_concepts <- c("käsite","käsite englanniksi","merkitys")
colnames(consepts1.df) <- cols_concepts

#%>%
#  arrange(Term) %>% # i.e. alphabetical order by Term
#  kable(booktab = T) # booktab = T gives us a pretty APA-ish table
knitr::kable(arrange(consepts1.df, consepts_fi),booktab=TRUE )
#knitr::kable(consepts1.df, booktab=TRUE)

```

Ed Berryn [esimerkin](https://eddjberry.netlify.com/post/writing-your-thesis-with-bookdown/) mukaan

# Linkit ISSP-datan dokumetteihin (21.12.18)

Data ja tärkeimmät dokumentit löytyvät GESIS - instituutin [data-palvelusta] (http://zacat.gesis.org).


```{r ISSPdocsTable, fig.cap="ISSP 2012 - Family and Changing Gender Roles IV - dokumentit"}
issp_docname <- c("Variable Report", "Study Monitoring Report","Basic Questionnaire", 
                  "Contents of ISSP 2012 module")
issp_docdesc <- c("Perusdokumentti, muuttujien kuvaukset ja taulukot", 
                  "tiedokeruun toteutus eri maissa", 
                  "Maittain sovellettava kyselylomake", "substanssikysymykset taulukkona")
issp_docfile <- c("ZA5900_cdb.pdf", "ZA5900_mr.pdf", "ZA5900_bq.pdf","ZA5900_overview.pdf")

ISSPdocsT.df <- data_frame(issp_docname, issp_docdesc, issp_docfile)
col_isspdocs <- c("dokumentti","sisältö","tiedosto")
colnames(ISSPdocsT.df) <- col_isspdocs

knitr::kable(ISSPdocsT.df, booktab=TRUE)

```

